language: node_js
sudo: required
services:
  - docker
branches:
  only:
    - main
before_install:
  # Clean install on any new build
  - npm run clean
jobs:
  include:
    - stage: lint jest compile and wdio
      script:
        - npm run lint
        - npm run jest
        - npm run wdio
stages:
  - lint jest compile and wdio
