language: node_js
sudo: required
services:
  - docker
branches:
  only:
    - main
before_install:
  # Clean install on any new build
  - npm run clean
jobs:
  include:
    - stage: lint jest compile and wdio
      script:
        - npm run lint
        - npm run jest
        - docker-compose up -d standalone-chrome-travis
        - npm run wdio
    - stage: deploy
      script:
        - rm -rf ./travis-build
        - npx terra release
stages:
  - lint jest compile and wdio
  - name: deploy
    if: type != pull_request
